Missing header on clang 23.1.0 (macOS 27.1, LLVM from homebrew)
```
  /Users/julien/Software/Others/EnergyPlus/third_party/Windows-CalcEngine/src/Common/src/SquareMatrix.cpp:91:13: error: use of undeclared
  identifier 'fill'
     91 |             fill(d.begin(), d.end(), 0)
```